# --- Basic options --- #

# Name of website
title: Ahmadhossein's website

# Short description of your site
description: A gentle introduction for myself

# Your name to show in the footer
author: Ahmadhossein Yazdani

# --- List of links in the navigation bar --- #

navbar-links:
  Home: "index"
  About Me: "aboutme"

# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/img/title-img.jpg"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
#round-avatar: false

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
#title-img: assets/img/title-img.jpg


# --- Footer options --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
# If you don't want to show a link to an RSS feed, set rss to "false".
social-network-links:
  email: "ahmadhossein.yazdani@gmail.com"
  #facebook: deanattali
  github: Ayazdani1997
  twitter: AhmadHYazdaniUT
  linkedin: ahmadhossein-yazdani-6560b3138
  telegram: AhmadHYazdaniUT

# --- General options --- #

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: false
  linkedin: true
  vk: false

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "My Website"

# Create a "tags" index page and make tags on each post clickable
link-tags: true

# Excerpt Word Length - Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# --- Colours / background image --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#314f96"
navbar-text-col: "white"
navbar-border-col: "#EAEAEA"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "black"
footer-text-col: "white"
footer-link-col: "#bf1290"

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/title-img.jpg"


title-separator: "-"

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"



# --- You don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Iran/Tehran"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      readtime: false # add estimated reading time on all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

