name: Docker Image CI (Upload Tag)

on:
  push:
    tags:
      - "v*"
    paths:
      - ".github/workflows/deploy-docker-tag.yml"
      - ".github/workflows/deploy-image.yml"
      - "bin/entry_point.sh"
      - "Dockerfile"
      - "Gemfile"
      - "Gemfile.lock"
      - "package.json"
      - "package-lock.json"

jobs:
  build:
<<<<<<< HEAD

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Buildx
      uses: docker/setup-buildx-action@v1
=======
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
>>>>>>> upstream/main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Buildx
        uses: docker/setup-buildx-action@v3

<<<<<<< HEAD
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
=======
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: amirpourmand/al-folio
>>>>>>> upstream/main

      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
